# Blockchain by example


version: '2'

volumes:
  orderer.fsc.com:
  peer0.org1.fsc.com:
  peer1.org1.fsc.com:
  peer0.org2.fsc.com:
  peer1.org2.fsc.com:
  peer0.org3.fsc.com:
  peer1.org3.fsc.com:

networks:
  fscn:

services:

  orderer.fsc.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.fsc.com
    container_name: orderer.fsc.com
    networks:
      - fscn

  peer0.org1.fsc.com:
    container_name: peer0.org1.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.fsc.com
    networks:
      - fscn

  peer1.org1.fsc.com:
    container_name: peer1.org1.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.fsc.com
    networks:
      - fscn

  peer0.org2.fsc.com:
    container_name: peer0.org2.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.fsc.com
    networks:
      - fscn

  peer1.org2.fsc.com:
    container_name: peer1.org2.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.fsc.com
    networks:
      - fscn

  peer0.org3.fsc.com:
    container_name: peer0.org3.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.fsc.com
    networks:
      - fscn

  peer1.org3.fsc.com:
    container_name: peer1.org3.fsc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.fsc.com
    networks:
      - fscn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.fsc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fsc.com/peers/peer0.org1.fsc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fsc.com/peers/peer0.org1.fsc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fsc.com/peers/peer0.org1.fsc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fsc.com/users/Admin@org1.fsc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.fsc.com
      - peer0.org1.fsc.com
      - peer1.org1.fsc.com
      - peer0.org2.fsc.com
      - peer1.org2.fsc.com
      - peer0.org3.fsc.com
      - peer1.org3.fsc.com
    networks:
      - fscn
